OBJ = \
		ClapTrap.o \
		ScavTrap.o \
		FragTrap.o \
		DiamondTrap.o \
		main.o \

all: diamond

diamond: $(OBJ)
	c++ $^ -o $@

%.o: %.cpp
	c++ -std=c++98 -Wall -Werror -Wextra -c $^ -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f diamond

re: fclean all

.PHONY: clean fclean re